### ISSUE TITLE
No index toggle [NEW Functionality] 

### ISSUE THREAD

**Issue by Reggie-Gonzalez** [on-associates/OTA-Insight#11]
Client requested no index toggle for the landing pages - future request to have the option to custom pick n choose pages

**Requirement:**

- CMS admin needs ability to hide a post (all content types) These pages would still be accessible via a link, but not automatically added to either a landing page, or index page.
- Pages would still load when users enter the url specifically for this page

@ianpamintuan to review Exclaimer/similar builds to see if we can adapt previous approach to hiding page cards from index pages

**Comment by ianpamintuan** [comment]
@Reggie-Gonzalez @leonmadebyon I think we did something similar on Exclaimer https://github.com/on-associates/exclaimer/issues/195

But this is only on a page level. I think we need to explore if this can be also applied to cards

**Comment by ianpamintuan** [comment]
@Reggie-Gonzalez @kmocorro Maybe we can add a `hideFromBlogIndex` property and we'll filter it using SB graphql

**Comment by Reggie-Gonzalez** [comment]
@ianpamintuan @kmocorro It would be helpful to hear a plan and the dev effort required before we action. @kmocorro After the categories work, lets find a stopping point to investigate
