### ISSUE TITLE
Multi-language font: Japanese - link issue in main nav

### ISSUE THREAD

**Issue by Reggie-Gonzalez** [on-associates/OTA-Insight#14]
We need a new fallback font to be implemented, as the existing font on site does not support japanese script.  

New font confirmation requested and supplied in this trello ticket, info below: https://trello.com/c/65KCyPEU/35-homepage-translations

I see indeed that both don’t support simplified Chinese or Japanese.
I think both can be replaced by Han Sans. That way we stay within the Adobe ecosystem and it looks like it can work shape-wise as well as weight-wise.

Can your team do the matching to the weights that they adopted for titles and body copy etc?

I’ll add the entire font family to our Adobe Font project

[Source Han Sans Japanese from Adobe Originals](https://fonts.adobe.com/fonts/source-han-sans-japanese#fonts-section)

Because of a bug on Adobe’s end, you cannot add Chinese or Japanese fonts to existing projects 🤦🏻‍♂️
This is why I needed to create a new project.

This is the embed code for the new project:
<script>
(function(d) {
var config = {
kitId: 'rgf8kvg',
scriptTimeout: 3000,
async: true
},
h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='[https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)](https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function()%7Ba=this.readyState;if(f%7C%7Ca&&a!=%22complete%22&&a!=%22loaded%22)return;f=true;clearTimeout(t);try%7BTypekit.load(config)%7Dcatch(e)%7B%7D%7D;s.parentNode.insertBefore(tk,s))
})(document);
</script>

**Comment by leonmadebyon** [comment]
We need to: 

- [ ] Implement new font as fallback, only to be used when:
>>>>  JP language selected from lang selector dropdown OR page served with /jp/ in url
- [ ] Test new homepage build with JP lang content
- [ ] Test new product page with JP lang
- [ ] Test links work with /jp/ being added

**Comment by leonmadebyon** [comment]
Bug in main nav - global nav links to /jp/ rather than /ja/ - and doubles /jp in url

![Image](https://github.com/on-associates/OTA-Insight/assets/98480098/a998403a-054c-4323-b40d-341685bb15f8)
