### ISSUE TITLE
Google Search: website is listed as 'OTA Insight.' vs. Lighthouse

### ISSUE THREAD

**Issue by lizzie-madebyon** [on-associates/OTA-Insight#18]
https://trello.com/c/Hj0iRNAT/157-google-search-website-is-listed-as-ota-insight-vs-lighthouse

The one outstanding suggested action is for ON team to review the use of url tags in site header, and check whether we can make changes here to help google capture the new company name.

**Comment by charlieeclarke** [comment]
@lizzie-madebyon The repo linked here appears to be empty weirdly and I have just done a search for OTA on our ON account and can't find any others. Do you know if it may be this one instead? https://github.com/on-associates/lighthouse

**Comment by lizzie-madebyon** [comment]
@charlieeclarke yes it is lighthouse! They had a rebrand from OTA to Lighthouse

**Comment by lizzie-madebyon** [comment]
Done & updated client - closing
