### ISSUE TITLE
SEO: Migration Mapping

### ISSUE THREAD

**Issue by Reggie-Gonzalez** [on-associates/OTA-Insight#3]
Client is taking migration mapping in-house. The requirement on our end is to review the final SEO migration map on 30/10, and implement the coded redirect file to the codebase. 

**Latest update**: Launch moved to 9/10 - chasing client to provide migration map no later than this wednesday on 2/11. 

- [ ] Review the final migration map on 02/11 (1/2 day task) reminding client to provide this no later than this Wednesday AM 1/11

**Comment by Reggie-Gonzalez** [comment]
@lizzie-madebyon added this ticket here for ollie. To begin, this is a question and I can update after into separate tickets if thats best.

**Comment by OllieBoydON** [comment]
Hey Reggie, do you have a link to the Figma sitemap? I can only find a link to the [Design System](https://www.figma.com/file/kJyVF2daHIhvzdHKEkQfZX/Lighthouse-Design-System-(OTA-TEAM)?type=design&node-id=7-3898&mode=design&t=NPr5SHVyXG91uzQo-0)?

**Comment by lizzie-madebyon** [comment]
@Reggie-Gonzalez just tagging you so you can see Ollie's message :)

**Comment by OllieBoydON** [comment]
Hey @Reggie-Gonzalez , Please find the URL recommendations and Title tags for OTA. As part of a new initiative, we're trying to highlight how pages fit within the buying cycle. https://docs.google.com/spreadsheets/d/1fOLsaNDHRomuPpjW_NOY-tz_boBQ9WhLyFzo3DDuVxU/edit?usp=sharing 

Firstly, everything here is based on an opinion than fact, so the client or others may differ for the odd page. However, I think it's important to have an understanding of how the website represents itself, and it mostly presumes you're already in the industry to find Lighthouse. The Awareness section may be larger on launch as it is only the blog really on that front.

**Comment by Reggie-Gonzalez** [comment]
Hi @lizzie-madebyon I updated the original ticket and added two items to the task list. Both are drafts I have written concerning SEO in the cms and a summary of how we address redirects - is it possible for Ollie to read them over and provide any notes for me? Any chance this can be done today? Should take 15 min possibly?

**Comment by OllieBoydON** [comment]
Hey Reggie, I've done to those docs and provided some feedback. 

In terms of the Boilerplate work, the one thing we don't help with, is the meta descriptions of the new website. Since these should be summaries of the page content, plus they can be very time consuming to complete on our side.

**Comment by Reggie-Gonzalez** [comment]
@lizzie-madebyon Client launch date has moved to 24/10. Have updated the timeline for the tasks above. Let me know if any questions!

**Comment by lizzie-madebyon** [comment]
Hey @Reggie-Gonzalez is this ticket ok to close?

**Comment by Reggie-Gonzalez** [comment]
hey @lizzie-madebyon this ticket is still open, we haven't completed the task. I have updated the date for delivery to this Thursday. I spoke with Ollie this am who had kept the last half of this week open for OTAI, so there's no issue. 

I will update this ticket on Wednesday with the client's migration map.

**Comment by lizzie-madebyon** [comment]
Closing as done
