### ISSUE TITLE
ContentBlocker: Card Solution Grid > Card Solution Grid Item

### ISSUE THREAD

**Issue by Reggie-Gonzalez** [on-associates/OTA-Insight#4]
CB: Content blocker 

- [x] Functionality: Current build is missing the additional txt field for description and a field for the url link to the role page
- [x] Styling: Hover state

Design in figma here 

![Image](https://github.com/on-associates/OTA-Insight/assets/112515096/960b403c-32b9-4350-ac9c-7f1f380060a0)

**Comment by kmocorro** [comment]
done
