### ISSUE TITLE
ContentBlocker: Category dropdown filter

### ISSUE THREAD

**Issue by Reggie-Gonzalez** [on-associates/OTA-Insight#8]
Loom [here ] please watch (https://www.loom.com/share/5ded99b4f36f443cb734dd03db25aa00?sid=dbaaef0b-aa76-4dbe-bec5-4825cf7a10f2)

- [x] Category needs to move to entry configuration and should have a predefined drop-down list to be added by client. See how tag drop-down is setup
- [x] Tag needs to rename as Content type
- [x] Category dropdown filter needs to be built in the resources index 

![Image](https://github.com/on-associates/OTA-Insight/assets/112515096/6b2e3d88-4219-48b9-9f20-23bde4ee24da)

**Comment by leonmadebyon** [comment]
Task:
- To review each page in turn as different pages have different drop-downs
-
